20220316 演習2-1～2-10　100％
ddt-shidana/meikai_java_shida pull request #2
Opened 2022-03-16 11:41 UTC by ddt-shidana

2022-03-23 11:29 UTC, ddt-mentor commented on ensyu02_01/src/ensyu02_01/Ensyu02_01.java
> +	//ここまでmainメソッド
柴田
閉じかっこに大してはコメントなしでも大丈夫です。

2022-03-23 11:59 UTC, ddt-mentor requested changes

2022-03-23 11:59 UTC, ddt-mentor commented on ensyu02_01/src/ensyu02_01/Ensyu02_01.java
> +		int x = 63.5, y = 18.2;
柴田
問題で指定されている場合を除き、1文字変数は使用しないでください。
（以降同様の指摘は行いません。）

2022-03-23 11:59 UTC, ddt-mentor commented on ensyu02_03/src/ensyu02_03/Ensyu02_03.java
> +		Scanner stdIn = new Scanner(System.in);
柴田
（修正不要、当コメントに対し、解答をお願いします。）
stdInとは何でしょうか？

※開発現場ではおそらく一般的な略称ではありますが、一般的な略称を除き、可能な限り略称は使用しないでください。

2022-03-23 11:59 UTC, ddt-mentor commented on ensyu02_03/src/ensyu02_03/Ensyu02_03.java
> +		//入力値が整数値よりも大きい箱の場合、エラーになります。
柴田
入力値が整数値よりも大きい場合、確かにエラーとなりますが、大きい「箱」とはどういうイメージでしょうか
（コメントに対し解答をお願いします。間違っていると思った場合は修正してください）

2022-03-23 11:59 UTC, ddt-mentor commented on ensyu02_08/src/ensyu02_08/Ensyu02_08.java
> +		System.out.println("その値の±5の乱数を生成しました。それは" + (randNum4 - 5) + "です。");
柴田
ほぼ、指定された結果は確かに得られますが、randNum4自体は±5の値ではありません。
こういう記載方法だとバグの元になるため、一度確実に±5の値を算出してから表示するよう修正してください

なお、結果は-5～+4となりますので間違っています。

2022-03-23 12:18 UTC, ddt-mentor commented on ensyu02_03/src/ensyu02_03/Ensyu02_03.java
> +		Scanner stdIn = new Scanner(System.in);
※補足
Scanner クラスの stdIn変数 ということではなく、stdInという文字は何かという意味です。

2022-09-14 11:15 UTC, ddt-shidana commented on ensyu02_03/src/ensyu02_03/Ensyu02_03.java
> +		Scanner stdIn = new Scanner(System.in);
standard input:標準入力

2022-09-14 11:15 UTC, ddt-shidana commented on ensyu02_03/src/ensyu02_03/Ensyu02_03.java
> +		//入力値が整数値よりも大きい箱の場合、エラーになります。
コメントを修正しました

2022-09-14 11:15 UTC, ddt-shidana commented on ensyu02_08/src/ensyu02_08/Ensyu02_08.java
> +		System.out.println("その値の±5の乱数を生成しました。それは" + (randNum4 - 5) + "です。");
コメントを修正しました。

2022-09-14 14:18 UTC, ddt-mentor commented on ensyu02_08/src/ensyu02_08/Ensyu02_08.java
> +		int randNum4 = rand.nextInt(11);
成田
nextInt(11)が返すのは0~11の乱数値ではないです。再度nextIntの挙動を調べましょう。

2022-09-14 14:18 UTC, ddt-mentor commented on ensyu02_08/src/ensyu02_08/Ensyu02_08.java
> +		}
成田
この上のif分を通ることがあるか確認してみて下さい。
まったく通らないのであれば不要な処理です。

2022-09-14 15:07 UTC, ddt-shidana commented on ensyu02_08/src/ensyu02_08/Ensyu02_08.java
> +		}
削除しました。

2022-09-14 15:07 UTC, ddt-shidana commented on ensyu02_08/src/ensyu02_08/Ensyu02_08.java
> +		int randNum4 = rand.nextInt(11);
コメントの0～11を修正しました。

2022-09-28 10:28 UTC, ddt-mentor requested changes

2022-09-28 10:28 UTC, ddt-mentor commented on ensyu02_08/src/ensyu02_08/Ensyu02_08.java
> +		//求めたいのは 入力値 + (0～11のランダムな値) - 5
柴田
細かい点ですが、こちらのコメント修正がされていないようです。
同じ修正が無いか、横展開チェックをする癖をつけるよう心掛けてください。

2022-09-28 10:41 UTC, ddt-shidana commented on ensyu02_08/src/ensyu02_08/Ensyu02_08.java
> +		//求めたいのは 入力値 + (0～11のランダムな値) - 5
修正分コミットしました。

2022-10-19 10:59 UTC, ddt-mentor requested changes

2022-10-19 10:59 UTC, ddt-mentor commented on ensyu02_07/src/ensyu02_07/Ensyu02_07.java
> +		int randNum1 = rand.nextInt(10);
0が含まれないようにする必要があるかと思います。(石井)

2022-11-02 11:17 UTC, ddt-mentor commented
成田
修正確認しました。

2022-11-02 11:17 UTC, merged