Ensyu04 02
ddt-shidana/meikai_java_shida pull request #7
Opened 2022-09-21 12:11 UTC by ddt-shidana

2022-09-28 10:39 UTC, ddt-mentor requested changes

2022-09-28 10:39 UTC, ddt-mentor commented on ensyu04_02/src/ensyu04_02/Ensyu04_02.java
> +			if (xInt > no) {
柴田
パッと見で変数名の意味が不明です。（数値であることと、何かの番号であることはわかります）
再度変数名を見直し、意味のある変数名に修正してください。
各コメントの修正漏れにご注意ください。変数名に意味を持たせると回避することができるかと思います。

2022-09-28 10:59 UTC, ddt-shidana commented on ensyu04_02/src/ensyu04_02/Ensyu04_02.java
> +			if (xInt > no) {
修正コミットしました。

2022-09-28 11:01 UTC, ddt-mentor requested changes

2022-09-28 11:01 UTC, ddt-mentor commented on ensyu04_02/src/ensyu04_02/Ensyu04_02.java
> +		int random_int = rand.nextInt(90) + 10;
柴田
細かいですが変数名の命名規則に則っていません。修正をお願いします。
※細かい箇所の積み重ねが綺麗なコードとなるか汚いコードとなるかを決めると私は考えています。

2022-11-02 11:33 UTC, ddt-mentor commented
成田
確認しました。

2022-11-02 11:33 UTC, merged